[project]
name = "agent-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "faiss-cpu>=1.15.1",
    "langchain>=1.4.2",
    "langchain-community>=0.4.2",
    "langchain-huggingface>=1.2.2",
    "langchain-openai>=1.6.2",
    "langchain-text-splitters>=1.1.2",
    "numpy>=2.5.3",
    "openai>=3.16.2",
    "pydantic-settings>=2.15.0",
    "python-dotenv>=1.2.3",
    "sentence-transformers>=6.1.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = [
    "src/agent_demo",
    "src/agent_demo/rag",
    "src/agent_langc",
    "src/agent_langc/rag"
]

[dependency-groups]
dev = [
    "hatchling>=1.32.3",
]
